project:
  type: website
  output-dir: docs
  render:
  - "*.md"
  - "*.qmd"
  - "!ignore.qmd"
  - "!ignore-dir/"

website:
  title: "telemetry"
  back-to-top-navigation: true
  reader-mode: true
  favicon: diginsight.jpg
  search: false
  open-graph: true
  image: diginsight.jpg
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - Diginsight v3 is now available"
    type: primary
    position: below-navbar    # location: navbar
    # type: overlay
    # keyboard-shortcut: ["?", "H"]
    # logo: bi-lightbulb diginsight.ico
    # language: 
    #     search-box-placeholder: Search    
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.md
      - text: "Concepts"
        href: src/docs/01. Concepts/00.01 - Observability Concepts.md
      - text: "Advanced articles"
        href: src/docs/02. Advanced/09.00 - Configure diginsight telemetry to the remote tools.md
      - text: "About"
        menu:
           - text: About
             href:  src/docs/05. About/about.md
           - text: License
             href:  src/LICENSE.md
        # href: about.qmd
    tools:
       # - icon: twitter
       #   href: https://twitter.com
       - icon: github
         menu:
           - text: Profile
             href:  https://github.com/diginsight
           - text: Source Code
             href:  https://github.com/diginsight/telemetry
           - text: Report a Bug
             href:  https://github.com/diginsight/telemetry
  # contents: auto
  sidebar:
    style: "docked"
    search: false
    contents:
    - text: Home
      href:  index.md
    - text: "---"
    - text: Getting Started
      href:  "src/docs/00.01 - Getting Started.md"
    - text: "---"
    - section: Concepts
      contents: "src/docs/01. Concepts/**"
    - text: "---"
    - section: Advanced Articles
      contents: "src/docs/02. Advanced/*"
    - text: "---"
    - section: Other
      contents: "src/docs/04. Other/*"
    # - text: "---"
    # - section: About
    #   contents: "src/docs/05. About/*"
    tools:
    # - icon: twitter
    #   href: https://twitter.com
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/diginsight
        - text: Report a Bug
          href:  https://github.com/diginsight
  page-footer: 
    left: "Copyright 2021, Diginsight" 
    border: false
    right: 
      - icon: github
        href: https://github.com/diginsight
      # - icon: twitter 
      #   href: https://twitter.com/         # - acknowlegment.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true