using Microsoft.CodeAnalysis;

namespace Diginsight.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class NonSealedAttributeGenerator : IIncrementalGenerator
{
    public const string AttributeName = "NonSealed";
    public static readonly string AttributeNamespace = typeof(NonSealedAttributeGenerator).Namespace!;

    private static readonly string AttributeSource =
        $"""
         // <auto-generated/>
         #nullable enable

         namespace {AttributeNamespace};

         [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
         internal sealed class {AttributeName}Attribute : global::System.Attribute;

         """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static postInitializationContext => postInitializationContext.AddSource($"{AttributeName}Attribute.g.cs", AttributeSource)
        );
    }
}
