<Project>

  <PropertyGroup>
    <RootNamespace Condition="$(RootNamespace.EndsWith('.Private'))">$(RootNamespace.Replace('.Private', ''))</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Diginsight.Analyzers.Private' AND '$(MSBuildProjectName)' != 'Diginsight.Analyzers.CodeFixes.Private'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)Diginsight.Analyzers.Private\Diginsight.Analyzers.Private.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)Diginsight.Analyzers.CodeFixes.Private\Diginsight.Analyzers.CodeFixes.Private.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0'))">
    <Features>runtime-async=on</Features>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable Condition="'$(IsPackable)' == ''">true</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>diginsight</Authors>
    <Product>Diginsight</Product>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/diginsight/telemetry</PackageProjectUrl>
    <PackageTags>diginsight</PackageTags>
    <!-- TODO <Description> in each csproj -->

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)diginsight.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.*" PrivateAssets="all" />
  </ItemGroup>

  <Choose>
    <When Condition="'$(GITHUB_ACTIONS)' == 'true'">
      <PropertyGroup>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <EnableSourceLink>false</EnableSourceLink>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)\packages.lock.json')">
    <Content Remove="packages.lock.json" />
    <None Remove="packages.lock.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="**/*.DotSettings" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)README.md">
      <Visible>false</Visible>
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="$(MSBuildThisFileDirectory)$(PackageIcon)" Condition="'$(PackageIcon)' != ''">
      <Visible>false</Visible>
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="$(MSBuildThisFileDirectory)LICENSE.md">
      <Visible>false</Visible>
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
